# Site settings
title: Scarlett & Jake
email: 
description: The wedding of the century! > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scarlettandjake.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
